version: '3.8'

services:
  shortlink:
    build: .
    container_name: shortlink-app
    restart: unless-stopped
    environment:
      - BASE_URL=https://shortlinks.sube.top
    ports:
      - "18000:8000"
    volumes:
      - ./data:/app/data

